### PR TITLE
Ensime 2.0 support

### PR DESCRIPTION
**Pull request by amanjpro**
This pull request addresses the bug #31

I tried to borrow as much code from the sbt counter part as possible. I removed the obsolete classes/methods (the ones that are no longer used after this pull request).

I have tested it, and will continue to improve it (as for now it is a bit slower than the sbt version, I think due to the use of coursier maybe)

I noticed that there is no active development on this project, I will be more than happy to take over this project if you agree.

### CODE REVIEW

**Comment by fommil** [comment]
oh wow, thanks! I will defer to somebody who understands this codebase to review/merge/release

**Comment by tanzoniteblack** [comment]
I won't have a chance to test this until I get home from work tonight, but I'll plan on doing that tonight. 

As long as I don't find any bugs while trying to use it, my only request is that you please squash the commits.

**Comment by fommil** [comment]
No need! Github does it now :-D

Select squash and merge at checkout.

**Comment by amanjpro** [comment]
@tanzoniteblack Sure, I will do it tomorrow.

**Comment by tanzoniteblack** [comment]
@amanjpro don't worry about the squashing, I can apparently do that when I merge it.

I tried running this, and it generated the ~.ensime~ file, but when trying to load it in emacs, I need to do something to get the 2.0 file loaded, and it gives directions for SBT. Is there something special you had to do to get this to load?

**Comment by fommil** [comment]
you're probably missing the server version

**Comment by fommil** [comment]
that whole test in emacs looks bogus... I don't think it is doing what I intended when we cut a stable release.

My guess is that you don't have the snapshot jars in the `:ensime-server-jars` field.

**Comment by amanjpro** [comment]
@tanzoniteblack thank you for your response. I am not using Emacs myself (I am a Vimmer), and I had no issue loading it (I didn't have to do anything special). It takes a while to be functional though.

Will add the mode Emacs and see what it is

**Comment by amanjpro** [comment]
Not sure if this helps, but I always clean and install the plugin then emit the .ensime configurations:

`$ mvn clean install && mvn ensime:generate`

**Comment by fommil** [comment]
vim might not have moved to using the new server format to launch the server, or might not do the version check. I added the check to emacs so that people wouldn't accidentally use v1 of the server.

**Comment by amanjpro** [comment]
I got the root of the problem, will fix it ASAP

**Comment by amanjpro** [comment]
@fommil @tanzoniteblack Now the ensime 2.0 jars are loaded and it works just fine under Emacs. Can you please make sure everything works.

**Comment by tanzoniteblack** [comment]
@amanjpro you have a couple instances in `ConfigGenerator.scala` where you're defaulting to common options if there's no override in the pom.xml (such as https://github.com/amanjpro/ensime-maven/blob/ensime2-support/src/main/scala/org/ensime/maven/plugins/ensime/ConfigGenerator.scala#L323 and https://github.com/amanjpro/ensime-maven/blob/ensime2-support/src/main/scala/org/ensime/maven/plugins/ensime/ConfigGenerator.scala#L338 )

2 things about these defaults:

1.) If the directories don't exist, it will prevent ensime from starting, so you should do a check to see if the directory actually exists before just assuming these as defaults
2.) ensime can be used to develop java projects as well, so the default of `/src/{main,test}/scala` would make more sense as `/src/{main,test}` instead. Honest, since I don't think the ensime cares about tests/sources, you could probably just default to `/src/` for these and forget the distinction when not set (provided that `src` is actually a directory in the project).

**Comment by fommil** [comment]
We will definitely start calling about main vs test soon :-)

We're planning a scalac per subproject and getting the deps correct. Right now, there is just one for the project.

Isn't that sort of information available from the build definition? I'm surprised you need to guess

**Comment by amanjpro** [comment]
@tanzoniteblack I will fix that (basically see if any of main or test exist for Java or Scala, and use it).

@fommil Those defaults are only used if the build-script does not have them.

**Comment by amanjpro** [comment]
@tanzoniteblack can you check this one?

**Comment by tanzoniteblack** [comment]
I'm still running into issues when trying to use this to generate a `.ensime` file for this project:

```Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: /Users/ryan/Programming/ensime-maven/src/test/java is required but does not exist```

**Comment by amanjpro** [comment]
Oh, can I know on which project you are running it? @tanzoniteblack

**Comment by amanjpro** [comment]
@tanzoniteblack can you help me to reproduce the exception? (see the above comment#edit2)

**Comment by amanjpro** [comment]
@fommil could you reproduce the exception? For some strange reason it does not happen on my machine, could be I am doing something wrong?

**Comment by fommil** [comment]
@amanjpro hi, sorry I don't use maven so we'll have to wait for @tanzoniteblack

**Comment by tanzoniteblack** [comment]
Sorry for being so very sluggish on this issue, I started a new job recently that no longer has me doing anything with maven or scala, so I haven't had much time to devote to looking into this.

@amanjpro I think the best way to solve this problem, is to instead of doing your filter for if the directory exists as part of creating `scalaSources`, do it at https://github.com/amanjpro/ensime-maven/blob/ensime2-support/src/main/scala/org/ensime/maven/plugins/ensime/ConfigGenerator.scala#L331 where you concatenate `scalaSources` with `module.getCompileSourceRoots`. That way the string that you're passing into the `.ensime` file can never have a directory that hasn't been checked to actually exist.

**Comment by amanjpro** [comment]
@tanzoniteblack thank you for taking care of this issue. I really appreciate it. And no worry, I also have recently started a new job and understand how stressful it can be. But in my case, the huge code base is in Scala + Maven. That is why I am really interested in this PR.

I have followed your suggestion, and just pushed a new commit. If you had time, I would be grateful if you could review it. As I stated earlier, if no one is going to actively maintain this project, I will happily volunteer to take it over.

**Comment by tanzoniteblack** [comment]
@amanjpro that fixed it for me! I'll go ahead and merge this in.

**Comment by tanzoniteblack** [comment]
@fommil would you possibly have a chance to go through the (overly) laborious process of releasing this as version 0.0.6 so people can start using it? 
Or do you remember if we ever got things set up to release automatically correctly?

**Comment by amanjpro** [comment]
Thank you @tanzoniteblack.

**Comment by fommil** [comment]
I don't believe I ever did the releases. I am happy to add @amanjpro as an owner of this repo. If you show this thread to the people at sonatype they should be able to give you access to publish to the `org.ensime.maven.plugins` groupId.

**Comment by amanjpro** [comment]
@fommil thank you, appreciated

**Comment by fommil** [comment]
@amanjpro would you like some ENSIME stickers? :smile: @chipsenkbeil should be able to send you some by snail mail.

**Comment by amanjpro** [comment]
Oh, thank you I have already got them + bonus stickers for both TypeLevel and Shapeless :) I think I need to share a photo of my computer in its new dress :)

**Pull request merged**
