### PR TITLE
Fix for https://github.com/ensime/ensime-maven/issues/21

### PR DESCRIPTION
**Pull request by kpadmasola**
+ on Windows, check for javac.exe instead of javac when  verifying if JDK is installed.

+ escape the backslashes in paths (Windows paths have backslash as file separator).

### CODE REVIEW

**Comment by tanzoniteblack** [comment]
@kpadmasola , not sure if you can see the result of the build failing or not, but all tests and what not passed, the failure is that the builder seems to think it was supposed to have pushed this to nexux-central-snapshots...which it's only supposed to do on builds of `master`. Not sure what's up with why the script seems to have $CI_BRANCH set to master, @fommil ?

**Comment by kpadmasola** [comment]
@tanzoniteblack, I noticed that too. Seems to be some configuration related issue.

**Comment by fommil** [comment]
Lgtm are you expecting the ci to fail? It would be good to get that fixed

**Comment by kpadmasola** [comment]
@fommil, I'm not sure how to fix this, would appreciate any pointers on how to go about fixing the build failure. The failure seems to be:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project ensime-maven: Failed to deploy artifacts: Could not transfer artifact org.ensime.maven.plugins:ensime-maven:jar:0.0.4-20160209.180635-5 from/to sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots): Failed to transfer file: https://oss.sonatype.org/content/repositories/snapshots/org/ensime/maven/plugins/ensime-maven/0.0.4-SNAPSHOT/ensime-maven-0.0.4-20160209.180635-5.jar. Return code is: 401, ReasonPhrase: Unauthorized. -> [Help 1]
```

**Comment by fommil** [comment]
@parsnips ?

**Comment by parsnips** [comment]
Seems like the sontaype credentials are not being used.

Most likely need to specify the .settings.xml file on [line 10](https://github.com/ensime/ensime-maven/blob/df7784a4f905eb8e5f75aecae17764199a27b6ee/.drone.yml#L10) like it is on [line 12](https://github.com/ensime/ensime-maven/blob/df7784a4f905eb8e5f75aecae17764199a27b6ee/.drone.yml#L12)

**Comment by kpadmasola** [comment]
@parsnips, I made the [suggested](https://github.com/ensime/ensime-maven/pull/23#issuecomment-182582763) change in `.drone.yml` and pushed, but the CI is still failing. The failure is in the `deploy` phase, not the `install` phase. The error is `401 Unauthorized`. Could it be that the credentials are wrong or expired in the CI environment?

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project ensime-maven: Failed to deploy artifacts: Could not transfer artifact org.ensime.maven.plugins:ensime-maven:jar:0.0.4-20160211.023714-5 from/to sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots): Failed to transfer file: https://oss.sonatype.org/content/repositories/snapshots/org/ensime/maven/plugins/ensime-maven/0.0.4-SNAPSHOT/ensime-maven-0.0.4-20160211.023714-5.jar. Return code is: 401, ReasonPhrase: Unauthorized. -> [Help 1]
```

**Comment by fommil** [comment]
I might have to look at that

**Comment by tanzoniteblack** [comment]
I thought we weren't even supposed to be trying to push the build unless
the branch was master?

**Comment by fommil** [comment]
That's true. Can you then update the drone file to do the same as ensime-server?

**Comment by parsnips** [comment]
So [this](https://github.com/ensime/ensime-maven/blob/df7784a4f905eb8e5f75aecae17764199a27b6ee/.drone.yml#L11-L13) is somehow evaluating to true.... I'll use the [ensime-sbt](https://github.com/ensime/ensime-sbt/blob/cf59d14f865fb96f52d1d0337704fb8075dda418/.drone.yml#L17-L19) way, but in any case it appears the credentials may be messed up.

**Comment by parsnips** [comment]
Fixed so that pull requests aren't executing deploy target [here](https://github.com/ensime/ensime-maven/pull/24) but I suspect that there still is an issue with the credentials.

**Comment by tanzoniteblack** [comment]
Probably should've put this https://github.com/ensime/ensime-maven/pull/24#issuecomment-183015171 comment here instead.

But the drones should now not attempt to deploy to maven-snapshots for non-master branches thanks to @parsnips fix. @kpadmasola if you rebase your changes on master, the tests should pass now.

**Comment by parsnips** [comment]
@fommil looks like we may need a new .drone.sec?

**Pull request merged**
