### PR TITLE
Add ensime-server-version to config.

### PR DESCRIPTION
**Pull request by dangerousben**

### CODE REVIEW

**Comment by amanjpro** [comment]
Thanks for the PR. Can you elaborate why this is needed? I haven't been following the project for the last few months and I have sadly fell behind a bit.

And, if you sign the license agreement, so I can merge the PR

**Comment by dangerousben** [comment]
> Thanks for the PR. Can you elaborate why this is needed? I haven't been following the project for the last few months and I have sadly fell behind a bit.

It's a recent addition to the config file format, see https://github.com/ensime/ensime-emacs/blob/master/ensime-startup.el#L147

As to exactly why it's needed in addition to ensime-server-jars - not sure, you'd have to ask @fommil (I think maybe it just makes it easier for editors to detect whether they're dealing with an old server version).

**Comment by fommil** [comment]
Yup, that's the reason.

**Review by amanjpro — APPROVED** [review]
LGTM

**Pull request merged**
