### PR TITLE
Update scala version to work with Java 8

### PR DESCRIPTION
**Pull request by tanzoniteblack**
Using scala version 2.10.0-M7 there are compilation issues using Java
8. In order to upgrade scala versions, I also needed to update the
environment variables and versions regarding scala-io-core and specs2,
otherwise the pom attempted to download dependencies that didn't exist.

### CODE REVIEW

**Comment by fommil** [comment]
@parsnips how's this looking?

**Comment by parsnips** [comment]
+1 this branch passed tests on my machine and looks good. Thanks @tanzoniteblack

**Comment by fommil** [comment]
@parsnips if you accept the request to become a member, you'll be able to merge.

**Comment by fommil** [comment]
also, we can set up CI for you if you want. Just create a `.drone.yml` file doing what you think it should do based on the ensime-server one and I'll enable the repo (you might need to issue some commands to install maven)

**Comment by parsnips** [comment]
@fommil Can you give me write permissions to this repo?  Thanks!

**Comment by fommil** [comment]
I gave you an invite earlier in the day (sorry, should have done this AGES ago)

BTW, Aemon has a patch for Java support :-) so this plugin is about to get much more popular :-)

**Comment by parsnips** [comment]
Yeah I'm a member of the Ensime org now, but I think you need to give this repo permissions to the repositories via https://github.com/orgs/ensime/teams/maven-panel

**Comment by parsnips** [comment]
Also super excited about the java patch!!!

**Comment by fommil** [comment]
Doh!

**Comment by fommil** [comment]
Fixed

**Comment by fommil** [comment]
Let's get this repo set up on drone too. First things first, if you have a moment, change the artifact group I'd to org.ensime

**Comment by parsnips** [comment]
Yeah, i'll spend some quality time tonight on it :)

**Comment by fommil** [comment]
OK, I'll enable it now. Should just start to work when you add the definition file

**Pull request merged**
