### PR TITLE
Update version to 0.0.4-SNAPSHOT

### PR DESCRIPTION
**Pull request by tanzoniteblack**
0.0.3 has now been released to sonatype

### CODE REVIEW

**Comment by fommil** [comment]
woot! All the more important as we increase our Java support. Which fields are supported now?

**Comment by tanzoniteblack** [comment]
For root project:

"root-dir"
"cache-dir"
"name"
"scala-version"
"java-home"
"java-flags"
"subprojects"
"formatting-prefs"

For subprojects:

"name"
"module-name"
"version"
"runtime-deps"
"compile-deps"
"test-deps"
"source-roots"
"target"
"test-target"
"reference-source-roots"
"depends-on-modules"

Formatting preferences (currently read from a properties file, not the maven scalariform plugin, I should make an issue for that support):

"indentSpaces"
"indentWithTabs"
"alignParameters"
"doubleIndentClassDeclaration"
"alignSingleLineCaseStatements"
"alignSingleLineCaseStatements.maxArrowIndent"
"indentPackageBlocks"
"indentLocalDefs"
"spaceBeforeColon"
"compactStringConcatenation"
"spaceInsideBrackets"
"spaceInsideParentheses"
"preserveSpaceBeforeArguments"
"spacesWithinPatternBinders"
"multilineScaladocCommentsStartOnFirstLine"
"placeScaladocAsterisksBeneathSecondAsterisk"
"formatXml"
"rewriteArrowSymbols"
"preserveDanglingCloseParenthesis"
"compactControlReadability"

**Comment by fommil** [comment]
cool! Don't forget `:compiler-jars`, which is an editor feature for launching with assembly jars instead of the sbt update mechanism.

**Comment by tanzoniteblack** [comment]
Would you mind opening an issue for that along with a link to the ensime-server or the sbt plugin that will help me know what to put into that field?

**Comment by tanzoniteblack** [comment]
Oh, wait, is that what https://github.com/ensime/ensime-maven/issues/14 is?

**Pull request merged**
